language: go
go:
- 1.12
os:
- osx
env:
  global:
  - secure: U4CTf4UB88XHyVGUhiCUvk/NNjkfokI6KX1uQEXkHZOp9X4JOEO295vbLETRgMHO9l4lhAouKZOJ47G6RD4PggTcheVsNxvUVeOUZ3UPtKOzte2Qpou1PGQjdnPUMj8rC+c7Hgc5C8GK9B3o1OmNzyNtDpux+xzbxZUKpCl0kW1UKCOKKApx6WWZWBNt3QeHS8q/8MO/OM/jm1G9o1U0WPx8b2dnzibpY2LcboNAPOPK5grauHoIWF/ABpq2iInB1viOTX2Zl1F/tFAGQ2Hon3BAzan1g/bjXnUKaJwz4Y/kSCBYJMxR4Pn6U60qNXYfAExYdlBMcTlJkNSfSySbivs7qROKz7ncrak025IeXaUpnmllNh+nQAZtDJhIHXfwGg+beoX/ShpkFGN4bBJjEoRAe0gY7siG6Es4RfHNThDXeWR4mGq2x5SwQV7ALpTeLUQufpGOHF3cBIu6Kb355rMkLui5zjLt/qifMAhcDC10q1Dbk6bJlWK9YDeJGhfFUIXY6+twNUksol+GGWRUchWp1LCAI0n9aeQPMEXsDZ3H4kkaTkFodcI2zIO5qYoGSpoP6/1F1naQ1pY7z5Ps8er/BBWbvB9ctBDPCmTIjHh7MHzV8BV0xPV9/NVNu+gEqF6y0C/+e8/KVSsWaVYj5ghuLeotO60NHmGhOOwqH7c=
before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
jobs:
  include:
  - stage: test
    script:
    - go get github.com/mattn/goveralls
    - go get -u github.com/rakyll/gotest
    - gotest -v -covermode=count -coverprofile=coverage.out ./ ./wal/... ./memdb/...
    - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-pro"